<?php
use Magento\Swatches\Model\Swatch;

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */

/** @var \EcomHouse\ProductVariants\ViewModel\ProductVariants $viewModel */
$viewModel = $block->getData('view_model');

$collection = $viewModel->getOptionsVariantsArray();
?>
<div class="product-variants swatch-attribute">
    <?php foreach ($collection as $item): ?>
        <div class="variants">
            <span class="swatch-attribute-label"><?= $item['label'] ?></span>
            <div class="swatch-attribute-options clearfix">
                <?php foreach ($item['values'] as $value): ?>
                    <a href="<?= $value['path'] ?>">
                        <?php if ($value['swatch_type'] === Swatch::SWATCH_TYPE_VISUAL_IMAGE): ?>
                            <div class="variant swatch-option text <?= $value['class'] ?>">
                                <img src="/media/attribute/swatch<?= $value['swatch_value'] ?>"
                                     alt="<?= $value['attribute_text'] ?>">
                            </div>
                        <?php elseif ($value['swatch_type'] === Swatch::SWATCH_TYPE_VISUAL_COLOR): ?>
                            <div class="variant swatch-option text <?= $value['class'] ?>"
                                 style="background: <?= $value['swatch_value']; ?>"></div>
                        <?php else: ?>
                            <div class="variant swatch-option custom-option-text text <?= $value['class'] ?>">
                                <span><?= $value['attribute_text'] ?></span>
                            </div>
                        <?php endif; ?>
                    </a>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>
