<?php
/**
 * Template for block \Magento\Customer\Block\Adminhtml\Edit\Tab\Tab
 */
/** @var $block \Magento\Customer\Block\Adminhtml\Edit\Tab\Tab */
?>
<div class="fieldset-wrapper">
    <div class="fieldset-wrapper-title">
        <strong class="title"><?= $block->escapeHtml(__("Select products")); ?></strong>
    </div>
    <div class="admin__fieldset-wrapper-content">
        <fieldset class="admin__fieldset">
            <?= $block->getChildHtml(); ?>
        </fieldset>
    </div>
</div>
